/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 /home/arboleda/Code/oakarboleda/public/Space_rocket.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Space_rocket.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Rocket.geometry} material={materials.Material} position={[-0.002, 5.514, 0]} />
    </group>
  )
}

useGLTF.preload('/Space_rocket.glb')
